
// This file has been generated by the GUI designer. Do not modify.
namespace Toys
{
	public partial class Window
	{
		private global::Gtk.Fixed fixed1;

		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.EventBox eventbox2;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Toys.Window
			this.Name = "Toys.Window";
			this.Title = global::Mono.Unix.Catalog.GetString("Window");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Toys.Window.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow1.WidthRequest = 154;
			this.scrolledwindow1.HeightRequest = 296;
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.VscrollbarPolicy = ((global::Gtk.PolicyType)(0));
			this.scrolledwindow1.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			w1.Add(this.fixed2);
			this.scrolledwindow1.Add(w1);
			this.fixed1.Add(this.scrolledwindow1);
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.eventbox2 = new global::Gtk.EventBox();
			this.eventbox2.WidthRequest = 141;
			this.eventbox2.HeightRequest = 98;
			this.eventbox2.Name = "eventbox2";
			this.fixed1.Add(this.eventbox2);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.eventbox2]));
			w5.X = 199;
			w5.Y = 25;
			this.Add(this.fixed1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 342;
			this.Show();
		}
	}
}
